# Generated by Django 5.2.12 on 2026-05-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('rating', models.FloatField(default=0)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
