# Generated by Django 5.2.12 on 2026-05-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_seed_initial_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='books/images/'),
        ),
    ]
