# Generated by Django 5.2.12 on 2026-05-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
